{% set name = "exactextract" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exactextract-{{ version }}.tar.gz
  sha256: 5e96ee444efd65af69b8d930d14aefa0c2d212d115076590f5d57799ff5cd8f7

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py==38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ stdlib("c") }}
  host:
    - python
    - geos
    - libgdal
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - exactextract
  commands:
    - pip check  # [build_platform == target_platform]
  requires:
    - pip

about:
  home: https://github.com/isciences/exactextract
  summary: Fast and accurate raster zonal statistics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbaston
    - akrherz
