{% set name = "exactextract" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/exactextract-{{ version }}.tar.gz
  sha256: 776b5619a1642f674e8575cee9d5b8dfa756d9b4a81a73c2749773557a3d4871

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3
  skip: True  # [win or py==38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - {{ stdlib("c") }}
  host:
    - python
    - geos
    - libgdal
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - exactextract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/isciences/exactextract
  summary: Fast and accurate raster zonal statistics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbaston
    - akrherz
